"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { apiFetch, Career, readableError } from "@/app/lib/api";

export default function CareerApplicationForm(){
  const [career,setCareer]=useState<Career|null>(null);const [loading,setLoading]=useState(true);const [submitting,setSubmitting]=useState(false);const [error,setError]=useState("");const [sent,setSent]=useState(false);
  useEffect(()=>{const id=new URLSearchParams(window.location.search).get("career");apiFetch<{careers:Career[]}>("/careers").then((data)=>setCareer(data.careers.find((item)=>item.id===id)||null)).catch((err)=>setError(readableError(err))).finally(()=>setLoading(false));},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!career)return;setSubmitting(true);setError("");try{await apiFetch(`/careers/${career.id}/applications`,{method:"POST",body:new FormData(event.currentTarget)});setSent(true);window.scrollTo({top:0,behavior:"smooth"});}catch(err){setError(readableError(err));}finally{setSubmitting(false);}}
  if(loading)return <section className="inner-section"><p className="dashboard-state">Loading role...</p></section>;
  if(!career)return <section className="inner-section application-state"><h2>Role unavailable.</h2><p>This position is no longer accepting applications.</p><Link className="inner-link" href="/careers">View current openings</Link></section>;
  if(sent)return <section className="inner-section application-state"><span>APPLICATION RECEIVED</span><h2>Thank you, we have it.</h2><p>Your application for {career.title} was submitted successfully. The team will contact you if your experience matches the next stage.</p><Link className="inner-link" href="/careers">Return to careers</Link></section>;
  return <section className="inner-section application-layout"><aside><p className="section-label">APPLYING FOR</p><h2>{career.title}</h2><div className="career-meta"><span>{career.department}</span><span>{career.employment_type}</span><span>{career.location}</span></div><p>{career.summary}</p><small>Applications are reviewed privately by authorized AKELUWA SH administrators.</small></aside><form className="career-application-form" onSubmit={submit}><div className="editor-grid"><label>Full name<input name="full_name" autoComplete="name" required minLength={2} maxLength={120}/></label><label>Email address<input name="email" type="email" autoComplete="email" required/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" required minLength={5} maxLength={40}/></label><label>Current location<input name="location" autoComplete="address-level2" required/></label><label>LinkedIn profile <small>optional</small><input name="linkedin_url" type="url" placeholder="https://linkedin.com/in/..."/></label><label>Portfolio or GitHub <small>optional</small><input name="portfolio_url" type="url" placeholder="https://..."/></label><label className="wide-field">Why are you a good fit?<textarea name="cover_note" required minLength={20} maxLength={5000} placeholder="Tell us about your relevant experience, interests and availability."/></label><label className="wide-field file-field">Resume<input name="resume" type="file" accept=".pdf,.doc,.docx" required/><small>PDF, DOC or DOCX. Maximum 5 MB.</small></label><label className="wide-field application-consent"><input name="consent" type="checkbox" value="true" required/><span>I confirm this information is accurate and consent to AKELUWA SH storing and reviewing it for recruitment purposes.</span></label></div>{error&&<p className="form-alert is-error" role="alert">{error}</p>}<button className="portal-primary" disabled={submitting}>{submitting?"Submitting application...":"Submit application"}</button></form></section>;
}
