"use client";

import { useEffect, useMemo, useRef } from "react";
import Image from "next/image";
import QRCode from "qrcode";
import { Contract } from "@/app/lib/api";
import { siteURL } from "@/app/lib/site";

const sections: Array<[keyof Contract, string]> = [
  ["scope", "1. Scope of work"],
  ["deliverables", "2. Deliverables and acceptance"],
  ["milestones", "3. Milestones and schedule"],
  ["payment_terms", "4. Payment terms"],
  ["revision_terms", "5. Revisions and change requests"],
  ["support_terms", "6. Support and maintenance"],
  ["ownership_terms", "7. Intellectual property and ownership"],
  ["confidentiality_terms", "8. Confidentiality"],
  ["termination_terms", "9. Termination"],
  ["dispute_terms", "10. Governing law and disputes"],
  ["special_terms", "11. Additional terms"],
];

function date(value?: string) {
  if (!value) return "Not issued";
  return new Date(value.includes("T") ? value : `${value}T00:00:00`).toLocaleDateString(undefined, {
    year: "numeric", month: "short", day: "numeric",
  });
}

export default function ContractDocument({ contract }: { contract: Contract }) {
  const providerLegalName = contract.provider_legal_name || contract.provider_name;
  const issued = contract.sent_at || contract.created_at;
  return <article className="contract-paper" id={`contract-${contract.id}`}>
    <div className="contract-watermark" aria-hidden="true">
      <Image src="/company-logo.png" alt="" width={320} height={320} unoptimized />
      <strong>AKELUWA SH</strong><span>CONTROLLED CONTRACT COPY</span>
    </div>

    <header className="contract-letterhead">
      <div className="contract-brand-lockup">
        <Image src="/company-logo.png" alt="AKELUWA SH" width={76} height={76} unoptimized priority />
        <div><span>PROJECT AGREEMENT</span><strong>{contract.provider_name}</strong><small>{providerLegalName}</small></div>
      </div>
      <div className="contract-reference">
        <span>Document reference</span><strong>{contract.contract_number}</strong>
        <small>Version {contract.version} / issued {date(issued)}</small>
        <b className={`contract-status status-${contract.status}`}>{contract.status}</b>
      </div>
    </header>

    <section className="contract-title-block">
      <span>Binding project record</span><h2>{contract.title}</h2>
      <p>This agreement records the services, responsibilities, schedule, fees, and acceptance terms between the parties identified below.</p>
    </section>

    <section className="contract-parties" aria-label="Contract parties">
      <Party title="Service provider" name={providerLegalName} secondary={contract.provider_name !== providerLegalName ? contract.provider_name : ""} details={[contract.provider_address, contract.provider_email, contract.provider_phone, contract.provider_website]} identifiers={[contract.provider_registration_number && `Registration: ${contract.provider_registration_number}`, contract.provider_tax_id && `Tax ID: ${contract.provider_tax_id}`]} />
      <Party title="Client" name={contract.client_name} secondary={contract.client_company || ""} details={[contract.client_email]} identifiers={[]} />
    </section>

    <section className="contract-commercial" aria-label="Commercial summary">
      <div><span>Project period</span><strong>{date(contract.start_date)} to {date(contract.end_date)}</strong></div>
      <div><span>Contract value</span><strong>{contract.currency} {(contract.amount_cents / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</strong></div>
    </section>

    <div className="contract-clauses">{sections.filter(([key]) => contract[key]).map(([key, title]) => <section key={key}><h3>{title}</h3><p>{String(contract[key])}</p></section>)}</div>

    <section className="contract-authenticity">
      <div><span>Document fingerprint / SHA-256</span><code>{contract.content_hash || "Created when this draft is sent and locked"}</code></div>
      <dl>
        <div><dt>Reference</dt><dd>{contract.contract_number}</dd></div>
        <div><dt>Version</dt><dd>{contract.version}</dd></div>
        <div><dt>Issued</dt><dd>{date(contract.sent_at)}</dd></div>
        <div><dt>Record status</dt><dd>{contract.status}</dd></div>
      </dl>
      <p>The fingerprint identifies the locked commercial content and company identity snapshot stored for this version. Any change to those fields produces a different fingerprint.</p>
      {contract.content_hash && <ContractVerificationMark contract={contract} />}
    </section>

    <section className="contract-acceptance">
      <h3>Electronic acceptance record</h3>
      <p>Each signature below records acceptance of this contract reference and version. Signing timestamps are generated by the server.</p>
      <div className="contract-signatures">
        <SignatureRecord label="For the service provider" name={contract.provider_signer_name} signature={contract.provider_signature} signedAt={contract.provider_signed_at} />
        <SignatureRecord label="For the client" name={contract.client_signer_name} signature={contract.client_signature} signedAt={contract.client_signed_at} />
      </div>
    </section>

    <footer><strong>{contract.contract_number} / VERSION {contract.version}</strong><span>AKELUWA SH / CONTROLLED ELECTRONIC RECORD</span><p>This record includes electronic signatures and an integrity fingerprint; it is not represented as a licensed certificate-based digital signature. The parties should obtain legal review appropriate to their jurisdiction and risk.</p></footer>
  </article>;
}

function ContractVerificationMark({ contract }: { contract: Contract }) {
  const canvas = useRef<HTMLCanvasElement>(null);
  const verificationURL = useMemo(() => {
    const url = new URL("/verify-contract", siteURL);
    url.searchParams.set("number", contract.contract_number);
    url.searchParams.set("fingerprint", contract.content_hash);
    return url.toString();
  }, [contract.content_hash, contract.contract_number]);

  useEffect(() => {
    if (!canvas.current) return;
    void QRCode.toCanvas(canvas.current, verificationURL, {
      width: 92,
      margin: 1,
      errorCorrectionLevel: "M",
      color: { dark: "#172554", light: "#ffffff" },
    });
  }, [verificationURL]);

  return <div className="contract-verification-mark">
    <canvas ref={canvas} role="img" aria-label="Contract verification QR code" />
    <div><span>Independent verification</span><strong>Scan or open the verification link</strong><a href={verificationURL}>{verificationURL}</a></div>
  </div>;
}

function Party({ title, name, secondary, details, identifiers }: { title: string; name: string; secondary: string; details: Array<string | undefined>; identifiers: Array<string | undefined> }) {
  const present = (items: Array<string | undefined>) => items.filter((item): item is string => Boolean(item));
  return <div><span>{title}</span><strong>{name}</strong>{secondary && <b>{secondary}</b>}{present(details).map((item) => <small key={item}>{item}</small>)}{present(identifiers).map((item) => <small className="contract-identifier" key={item}>{item}</small>)}</div>;
}

function SignatureRecord({ label, name, signature, signedAt }: { label: string; name: string; signature?: string; signedAt?: string }) {
  return <div><span>{label}</span><div className="contract-signature-mark">{signature ? <Image src={signature} alt={`${name} signature`} width={260} height={90} unoptimized /> : <i>Awaiting authorized signature</i>}</div><strong>{name || "Not signed"}</strong><small>{signedAt ? `Accepted ${new Date(signedAt).toLocaleString()}` : "Signature pending"}</small></div>;
}
